apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  labels: 
    app: nginx
#specification for deployment
spec:
  replicas: 3 #no of pod replicas needed.
  selector:
    matchLabels:
      app: nginx
  #template applies to Pod
  template: 
    metadata:
      labels:
        app: nginx
    #specification is the blueprint of a Pod
    spec:
      containers: 
      - name: nginx
        image: nginx:1.16
        ports:
        - containerPort: 8080     
