# 

trigger:
  branches:
    include:
    - main
  paths:
    exclude:
    - mydevops/arm/*
    - mydevops/azurecli/*
    - mydevops/azureps/*
    - mydevops/bibhumsnenv/*
    - mydevops/drawings/*
    - mydevops/k8samples/*
    - mydevops/terraforms/*
    - mydevops/.gitignore
    - mydevops/*.sh
    - mydevops/*.pem
    - mydevops/*.json

variables:
- group: TerraformVariableGroup #its a group of variable defined in the Pipeline Library in Azure DevOps
- name: subscription
  value: 'Visual Studio Subscription - 113136'
- name: location
  value: 'westus'
- name: buildPlatform
  value: 'Any CPU'
- name: buildConfiguration
  value: 'release'
- name: artifactName
  value: 'drop'


stages:
- stage: Build
  displayName: 'Build Code'
  jobs:
  - job: Build
    pool:
      name: "MyBuildAgents"
      demands: node.js 

    steps:
    - task: PublishSymbols@2
      displayName: 'Publish symbols path'
      inputs:
        SearchPattern: '**\*.*'
        PublishSymbols: false
      enabled: false
      continueOnError: true

    - task: CopyFiles@2
      displayName: 'Copy Terraforms to: $(build.artifactstagingdirectory)/113136envsetup'
      inputs:
        SourceFolder: 113136envsetup/terraforms/k8clusters/bpm-cowbird-aks
        TargetFolder: '$(build.artifactstagingdirectory)/terraform'

    - task: PublishBuildArtifacts@1
      displayName: 'Publish Artifact'
      inputs:
        PathtoPublish: '$(build.artifactstagingdirectory)'
        ArtifactName: '$(artifactName)'
        publishLocation: 'Container'
      condition: succeededOrFailed()

- stage: Infrastructure
  displayName: 'Setup K8 Cluster'
  dependsOn: Build
  jobs:
  - template: setup-k8cluster-bpm-cowbird-aks-on-azure.yaml
    parameters:
      subscription: $(subscription)
      terraformstoragerg: $(terraformstoragerg)
      terraformstorageaccount: $(terraformstorageaccount)
      terraformcontainer: $(terraformcontainer)


