#apiVersion: v1
#kind: Namespace
#metadata:
#  name: ns2022
#  labels:
#    name: ns2022

#---
apiVersion: v1
kind: LimitRange
metadata:
  name: limit-range
  namespace: ns2022
spec:
  limits:
  - default:         #LimitRange admission controller allocate this default limits if not specified in the container deployment file
      cpu: "300m"
      memory: 512Mi
    defaultRequest:  #LimitRange admission controller allocate this default requests if not specified in the container deployment file
      cpu: "150m"
      memory: 64Mi
    max:             #It is the maximum limits one can specify in the container deployment file
      cpu: "300m"
      memory: 512Mi
    min:
      cpu: "150m"    #It is the maximum requests one can specify in the container deployment file
      memory: 64Mi
    type: Container

---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: resoure-quota
  namespace: ns2022
spec:
 hard:
    limits.cpu: "1.5"
    limits.memory: 4Gi
    requests.cpu: "1"
    requests.memory: 1Gi
    pods: "10"

