kubectl create -f 01-namespace.yaml
kubectl create -f 02-serviceaccount.yaml
kubectl create -f 03-secrets.yaml
kubectl create -f 04-configmaps.yaml
kubectl create -f 05-roles.yaml
kubectl create -f 06-clusterroles.yaml
kubectl create -f 07-rolebindings.yaml
kubectl create -f 08-clusterrolebindings.yaml
kubectl create -f 09-deployment-dashboard.yaml
kubectl create -f 10-service-dashoboard.yaml
kubectl create -f 11-deployment-metrics.yaml
kubectl create -f 12-service-metrics.yaml
kubectl create -f 13-ingress-routes.yaml
