kubectl delete -f 13-ingress-routes.yaml
kubectl delete -f 12-service-metrics.yaml
kubectl delete -f 11-deployment-metrics.yaml
kubectl delete -f 10-service-dashoboard.yaml
kubectl delete -f 09-deployment-dashboard.yaml
kubectl delete -f 08-clusterrolebindings.yaml
kubectl delete -f 07-rolebindings.yaml
kubectl delete -f 06-clusterroles.yaml
kubectl delete -f 05-roles.yaml
kubectl delete -f 04-configmaps.yaml
kubectl delete -f 03-secrets.yaml
kubectl delete -f 02-serviceaccount.yaml
kubectl delete -f 01-namespace.yaml
