---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mongodb
  namespace: ns2022
spec:
  serviceName: mongodb-headless-svc
  podManagementPolicy: OrderedReady
  replicas: 1
  updateStrategy:
    type: RollingUpdate
  selector:
    matchLabels:
      app.kubernetes.io/name: mongodb
      app.kubernetes.io/component: mongodb-pod
  template:
    metadata:
      labels:
        app.kubernetes.io/name: mongodb
        app.kubernetes.io/component: mongodb-pod
    spec:
      serviceAccountName: mongodb-serviceaccount
      securityContext:
        fsGroup: 1001
        sysctls: []
      containers:
      - name: mongodb-pod
        image: mongo:4.4.4
        imagePullPolicy: IfNotPresent
        securityContext:
          runAsNonRoot: true
          runAsUser: 1001
        envFrom:
        - configMapRef:
            name: mongodb-configmap
        - secretRef:
            name: mongodb-secret
        resources:
          limits:
            cpu: 500m
            memory: 256Mi
          requests:
            cpu: 100m
            memory: 128Mi
        ports:
        - containerPort: 27017
          name: mongodb
        livenessProbe:
          exec:
            command:
            - mongo
            - --disableImplicitSessions
            - --eval
            - "db.adminCommand('ping')"
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          successThreshold: 1
          failureThreshold: 6
        readinessProbe:
          exec:
            command:
            - bash
            - -ec
            - |
              mongo --disableImplicitSessions $TLS_OPTIONS --eval 'db.hello().isWritablePrimary || db.hello().secondary' | grep -q 'true'
          initialDelaySeconds: 5
          periodSeconds: 10
          timeoutSeconds: 5
          successThreshold: 1
          failureThreshold: 6
        volumeMounts:
          - mountPath: "/data/db"
            name: mongodb-mount
      volumes:
        - name: mongodb-mount
          persistentVolumeClaim:
            claimName: mongodb-local-pvc

---
apiVersion: v1
kind: Service
metadata:
  name: mongodb-headless-svc
  namespace: ns2022
spec:
  type: ClusterIP
  clusterIP: None
  selector:
    app.kubernetes.io/name: mongodb
    app.kubernetes.io/component: mongodb-pod
  ports:
  - port: 27017
    name: mongodb
    targetPort: mongodb

---
apiVersion: v1
kind: Service
metadata:
  name: mongodb-svc
  namespace: ns2022
spec:
  type: NodePort
  selector:
    statefulset.kubernetes.io/pod-name: mongodb-0
    #externalTrafficPolicy: Local
  ports:
  - port: 27017
    name: mongodbnode
    targetPort: mongodb
    nodePort: 30017

#---
#apiVersion: networking.k8s.io/v1
#kind: Ingress
#metadata:
#  name: mongodb-ingress
#  annotations:
#    kubernetes.io/ingress.class: nginx
#    nginx.ingress.kubernetes.io/ssl-redirect: "false"
#    nginx.ingress.kubernetes.io/use-regex: "true"
#    nginx.ingress.kubernetes.io/rewrite-target: /$1
#  namespace: ns2022
#spec:
#  rules:
#  - host: "mongodb.kube9t.com"
#    http:
#      paths:
#      - path: /(.*)
#        pathType: Prefix
#        backend:
#          service:
#            name: mongodb-svc
#            port:
#              number: 27017

