apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongodb-gui-deployment
spec:
  selector:
    matchLabels:
      app: mongodb-gui
  template:
    metadata:
      labels:
        app: mongodb-gui
    spec:
      containers:
        - name: mongodb-gui
          image: mongo-express
          env:
            - name: ME_CONFIG_MONGODB_SERVER
              value: "mongodb-0.mongodb-h-svc.ns2022.svc.cluster.local"
          ports:
          - containerPort: 8081
---
apiVersion: v1
kind: Service
metadata:
  name: mongodb-gui-service
spec:
  selector:
    app: mongodb-gui
  ports:
    - name: mongodb-gui
      protocol: TCP
      port: 8081
      targetPort: 8081

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: mongodb-gui-ingress
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
    nginx.ingress.kubernetes.io/use-regex: "true"
    nginx.ingress.kubernetes.io/rewrite-target: /$1
  namespace: ns2022
spec:
  rules:
  - host: "mongodbgui.kube9t.com"
    http:
      paths:
      - path: /(.*)
        pathType: Prefix
        backend:
          service:
            name: mongodb-gui-service
            port:
              number: 8081