apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: default-devops-role
  namespace: ns2022
rules:
  # Allow Dashboard to get, update and delete Dashboard exclusive secrets.
  - apiGroups: ["*","apps","extensions"]
    #resources: ["deployments","pods","services","secrets","configmaps","ingress"]
    resources: ["*"]
    verbs: ["get", "update", "delete", "list", "patch", "watch"]

