apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-ingress-controller
  namespace: ns2022
  labels:
    app: testing-cronjob
spec:
  replicas: 1
  selector:
    matchLabels:
      name: nginx-ingress-controller-pod
  template:
    metadata:
      name: nginx-ingress-controller-pod
      labels:
        name: nginx-ingress-controller-pod
    spec:
      containers:
        - name: nginx-ingress-controller-pod
          image: quay.io/kubernetes-ingress-controller/nginx-ingress:0.21.0
          resources:
            requests:
              memory: "64Mi"
              cpu: "50m"
            limits:
              memory: "128Mi"
              cpu: "500m"
      args: 
        - /nginx-ingress-controller 
        - --configmap=$(POD_NAMESPACE)/nginx-configmap
      env:
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
      ports:
        - name: http
          containerPort: 80
        - name: https
          containerPort: 443

---
apiVersion: v1
kind: Service
metadata:
  name: nginx-ingress-controller-svc
  namespace: ns2022
  labels:
    svc: nginx-ingress-controller-svc
spec:
  type: NodePort
  selector:
    app: nginx-ingress-controller-pod
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
    nodePort: 30080
  - port: 443
    targetPort: 443
    protocol: TCP
    nodePort: 30443



