apiVersion: v1
kind: LimitRange
metadata:
  name: mem-limit-range
  namespace: ns2022
spec:
  limits:
  - default:
      memory: 256Mi
    defaultRequest:
      memory: 64Mi
    type: Container

---
apiVersion: v1
kind: LimitRange
metadata:
  name: cpu-limit-range
  namespace: ns2022
spec:
  limits:
  - default:
      cpu: "500m"
    defaultRequest:
      cpu: "50m"
    type: Container