apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  labels: 
    app: nginx #label applied to
spec: #specification for deployment
  replicas: 2 #no of pod replicas needed.
  selector:
    matchLabels:
      app: nginx #label applied to replicaset. all pods with the same replicaset level are grouped for service layer to consume.
  template: #template applies to Pod
    metadata:
      labels:
        app: nginx #label applied to Pod
    spec: #specification is the blueprint of a Pod
      containers: 
      - name: nginx
        image: nginx:1.16
        ports:
        - containerPort: 80 #open on K8 cluster network     
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-service
spec:
  selector:
    app: nginx
  type: NodePort
  ports:
    - nodePort: 30011
      port: 80
      targetPort: 80