apiVersion: v1
kind: ConfigMap
metadata:
  name: mongo-db-configmap
  namespace: ns2022
data:
  ME_CONFIG_OPTIONS_EDITORTHEME: "ambiance"
  ME_CONFIG_MONGODB_SERVER: "devopsk8masternodelinuxvm.centralus.cloudapp.azure.com"
  ME_CONFIG_BASICAUTH_USERNAME: "mongoadmin"
  ME_CONFIG_BASICAUTH_PASSWORD: "passw0rd!"

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongo-db
spec:
  selector:
    matchLabels:
      app: mongo-db-pod
  template:
    metadata:
      labels:
        app: mongo-db-pod
    spec:
      containers:
      - name: mongo-db-pod
        image: mongo:latest
        envFrom:
        - configMapRef:
            name: mongo-db-configmap
        resources:
          limits:
            memory: "128Mi"
            cpu: "100m"
        ports:
        - containerPort: 27017
        - containerPort: 28017
