apiVersion: v1
kind: ConfigMap
metadata:
  name: mssql-db-configmap
  namespace: ns2022
data:
  ACCEPT_EULA: "Y"
  SA_PASSWORD: "passw0rd!"
  MSSQL_PID: "Express"
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mssql
  namespace: ns2022
spec:
  serviceName: mssql-h-svc
  replicas: 1
  selector:
    matchLabels:
      app: mssql-db-pod
  template:
    metadata:
      labels:
        app: mssql-db-pod
    spec:
      volumes:
        - name: mssql-db-storage
          persistentVolumeClaim:
            claimName: mssql-db-local-pvc
      containers:
        - name: mssql-db-pod
          image: mcr.microsoft.com/mssql/server:2017-latest-ubuntu
          envFrom:
          - configMapRef:
              name: mssql-db-configmap
          resources:
            limits:
              memory: "128Mi"
              cpu: "500m"
          ports:
          - containerPort: 1433
          volumeMounts:
            - mountPath: "/var/opt/mssql"
              name: mssql-db-storage
---
apiVersion: v1
kind: Service
metadata:
  name: mssql-h-svc
  namespace: ns2022
spec:
  selector:
    app: mssql-db-pod
  ports:
  - port: 3306
  clusterIP: None

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: mssql-db-ingress
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
    nginx.ingress.kubernetes.io/use-regex: "true"
    nginx.ingress.kubernetes.io/rewrite-target: /$1
  namespace: ns2022
spec:
  rules:
  - host: "mssql.kube9t.com"
    http:
      paths:
      - path: /(.*)
        pathType: Prefix
        backend:
          service:
            name: mysql-0.mysql-h-svc.ns2022.svc.cluster.local
            port:
              number: 1433