apiVersion: networking.k8s.io/v1
kind: Ingress
metadata: 
  name: ingress-northwind
spec:
  rules:  
  - http:
      paths:
      - path: /
        pathType: Prefix
        backend: 
          service:
            name: northwind-app-svc
            port: 
              number: 8080


