apiVersion: v1
kind: ConfigMap
metadata:
  name: northwind-app-configmap
  namespace: ingress-nginx
data:
  MYNWAPP_ENV: development
  MYNWAPP_PORT: "8080"
  MYNWAPP_ERRORLOG: "true"
  MYNWAPP_TRACKINGLOG: "true"

---
apiVersion: v1
kind: Secret
metadata:
  name: northwind-app-secret
  namespace: ingress-nginx
type: Opaque
data:
#  MYNWAPP_MONGO_URI: "mongodb://mongoadmin:passw0rd!@devopsmasterlinuxvm.centralus.cloudapp.azure.com:9003/northwind?authSource=admin&readPreference=primary&appname=MongoDB%20Compass&ssl=false"
#  MYNWAPP_SessionKey: sessionkey1
#  MYNWAPP_AuthTokenKey: authtoken1
#  MYNWAPP_GEOCODER_API_KEY: AIzaSyAFN7pm1QA20ojk8CA2tQnXzOHB1ryRGtM
#  base64 encoded values are set here
  MYNWAPP_MONGO_URI: bW9uZ29kYjovL21vbmdvYWRtaW46cGFzc3cwcmQhQGRldm9wc21hc3RlcmxpbnV4dm0uY2VudHJhbHVzLmNsb3VkYXBwLmF6dXJlLmNvbTo5MDAzL25vcnRod2luZD9hdXRoU291cmNlPWFkbWluJnJlYWRQcmVmZXJlbmNlPXByaW1hcnkmYXBwbmFtZT1Nb25nb0RCJTIwQ29tcGFzcyZzc2w9ZmFsc2U=
  MYNWAPP_SessionKey: c2Vzc2lvbmtleTE=
  MYNWAPP_AuthTokenKey: YXV0aHRva2VuMQ==
  MYNWAPP_GEOCODER_API_KEY: QUl6YVN5QUZON3BtMVFBMjBvams4Q0EydFFuWHpPSEIxcnlSR3RN

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: northwind-app
  namespace: ingress-nginx
  labels:
    app: northwind-app
  annotations:
    description: "It's a MVC demo built on NodeJs"
    developer: "Bibhu Prasad Mishra"  
    email: "bibhup_mishra@yahoo.com"  
spec:
  replicas: 2
  selector:
    matchLabels:
      app: northwind-app-pod
      type: front-end
  template:
    metadata:
      labels:
        app: northwind-app-pod
        type: front-end
    spec:
      containers:
      - name: northwind-app-pod
        image: bibhupmishra/node-northwind-app
        envFrom:
        - configMapRef:
            name: northwind-app-configmap
        - secretRef:
            name: northwind-app-secret
        resources:
          requests:
            memory: "64Mi"
            cpu: "50m"
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 8080
        readinessProbe:
          httpGet:
            path: /logout
            port: 8080
          initialDelaySeconds: 10
          periodSeconds: 5
          failureThreshold: 5
        livenessProbe:
          httpGet:
            path: /logout
            port: 8080
          initialDelaySeconds: 10
          periodSeconds: 5
          failureThreshold: 5
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions: 
              - key: "nodejs"
                operator: "In"
                values: 
                - "yes"
              - key: "dotnetcore"
                operator: "In"
                values: 
                - "yes"
      tolerations:
      - key: "app"
        operator: "Equal"
        value: "blue"
        effect: "NoExecute"
---
apiVersion: v1
kind: Service
metadata:
  name: northwind-app-svc
  namespace: ingress-nginx
  labels:
    svc: northwind-app-svc
spec:
  type: NodePort
  selector:
    app: northwind-app-pod
  ports:
  - port: 8080
    targetPort: 8080
    nodePort: 30090



