---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: mssql-db-local-pv
  namespace: ns2022
  labels:
    storage: mssql-db-local-pv
spec:
  capacity:
    storage: 7Gi
  volumeMode: Filesystem
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-storage
  local:
    path: /jenkins
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: storageNode
          operator: In
          values:
          - "local-drive-pv"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mssql-db-local-pvc
  namespace: ns2022
spec:
  selector:
    matchLabels:
      storage: mssql-db-local-pv
  resources:
    requests:
      storage: 7Gi
  volumeMode: Filesystem
  storageClassName: local-storage
  accessModes:
    - ReadWriteOnce