#this YAML is to setup devops dockers on devopsmasterlinuxvm.centralus.cloudapp.azure.com
#pre-requisite for this setup is docker and docker compose on the VM
version: "3"
services:
    jenkins:
        container_name: jenkins
        restart: always
        image: "jenkins/jenkins:lts"
        ports:
            - "9001:8080"
            - "9002:50000"
        volumes:
            - /dockerdata/jenkins_home:/var/jenkins_home
        depends_on:
            - sonarqube
  
    mongodb:
        container_name: mongodb
        restart: always
        image: "mongo"
        ports:
            - "9003:27017"
            - "9004:28017"
        environment:
            - ME_CONFIG_OPTIONS_EDITORTHEME="ambiance"
            - ME_CONFIG_MONGODB_SERVER="devopsmasterlinuxvm.centralus.cloudapp.azure.com"
            - ME_CONFIG_BASICAUTH_USERNAME="mongoadmin"
            - ME_CONFIG_BASICAUTH_PASSWORD="passw0rd!"
        volumes:
            - /dockerdata/mongodb:/data/db
            - /dockerdata/mongocofigdb:/data/configdb
        depends_on:
            - sonarqube

    mssqldb:
        container_name: mssqldb-express
        restart: always
        image: "mcr.microsoft.com/mssql/server:2017-latest-ubuntu"
        ports:
            - "9005:1433"
        environment:
            - ACCEPT_EULA="Y"
            - SA_PASSWORD="passw0rd!"
            - MSSQL_PID=Express
        volumes:
            - /dockerdata/mssql:/var/opt/mssql

    sonarqube:
        container_name: sonarqube
        restart: always
        image: "sonarqube:8.2-community"
        ports:
            - "9006:9000"
        environment:
            - SONAR_JDBC_URL="jdbc:sqlserver://devopsmasterlinuxvm.centralus.cloudapp.azure.com:9005;databaseName=sonarqube"
            - SONAR_JDBC_USERNAME="sonar"
            - SONAR_JDBC_PASSWORD="passw0rd!"
        volumes:
            - /dockerdata/sonarqube/conf:/opt/sonarqube/conf
            - /dockerdata/sonarqube/data:/opt/sonarqube/data
            - /dockerdata/sonarqube/logs:/opt/sonarqube/logs
            - /dockerdata/sonarqube/extensions:/opt/sonarqube/extensions
        depends_on:
            - mssqldb

    portainer:
        container_name: portainer
        restart: always
        image: "portainer/portainer"
        ports:
            - "9007:9000"
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
            - /dockerdata/portainer:/data
        depends_on:
            - sonarqube




