# 

trigger: none
#  branches:
#    include:
#    - main
#  paths:
#    exclude:
#    - mydevops/_azure_env_setup_bibhu_msn/*
#    - mydevops/drawings/*
#    - mydevops/sample_arm_templates/*
#    - mydevops/sample_azure_ps/*
#    - mydevops/sample_azurecli/*
#    - mydevops/sample_k8_yaml/*
#    - mydevops/sample_terraforms/*
#    - mydevops/.gitignore
#    - mydevops/*.sh
#    - mydevops/*.pem
#    - mydevops/*.json

schedules:
  - cron: "00 09 * * *"
    displayName: Daily 4:00 AM CT
    branches:
      include: 
      - main
    always: true
  - cron: "00 21 * * *"
    displayName: Daily 04:00 PM CT
    branches:
      include: 
      - main
    always: true

variables:
- group: TerraformVariableGroup #its a group of variables defined in the Pipeline Library in Azure DevOps. This line of code copy them over here.
- name: subscription
  value: 'Visual Studio Subscription - 113136'
- name: location
  value: 'westus'
- name: buildPlatform
  value: 'Any CPU'
- name: buildConfiguration
  value: 'release'
- name: artifactName
  value: 'drop'


stages:
- stage: Build
  displayName: 'Download Code'
  jobs:
  - job: Build
    pool:
      name: "MyBuildAgents"
      demands: node.js 
    steps:
    - task: PublishSymbols@2
      displayName: 'Publish symbols path'
      inputs:
        SearchPattern: '**\*.*'
        PublishSymbols: false
      enabled: false
      continueOnError: true

    - task: CopyFiles@2
      displayName: 'Copy Terraforms to: $(build.artifactstagingdirectory)/terraform'
      inputs:
        SourceFolder: _azure_env_setup_113136_ntt/terraforms/k8cluster-bpm-cowbird-aks
        TargetFolder: '$(build.artifactstagingdirectory)/terraform'

    - task: PublishBuildArtifacts@1
      displayName: 'Publish Artifact'
      inputs:
        PathtoPublish: '$(build.artifactstagingdirectory)'
        ArtifactName: '$(artifactName)'
        publishLocation: 'Container'
      condition: succeededOrFailed()

- stage: Infrastructure
  displayName: 'Setup K8 Cluster'
  dependsOn: Build
  jobs:
  - template: setup-k8cluster-bpm-cowbird-aks-on-azure.yaml
    parameters:
      subscription: $(subscription)
      terraformstoragerg: $(terraformstoragerg)
      terraformstorageaccount: $(terraformstorageaccount)
      terraformcontainer: $(terraformcontainer)


